name: react yavinenana

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    name: 'DEPLOY CD || checkout master -  aws s3 copy '
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
        env:
          API_URI: http://localhost:8000/graphql/
# deploy to aws s3
      - name: 'aws s3 copy'
        uses: jakejarvis/s3-sync-action@master
        with:
#          args: --follow-symlinks --exclude '.git/*' --exclude '.github/*' --delete
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}-qajordy
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_QA_GHA_S3_FULL }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA_GHA_S3_FULL }}
          AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository
          DEST_DIR: 'dashboard'
